# Application Variable
$terminal             =    kitty
$fileManager          =    pcmanfm
$menu                 =    rofi -show drun -theme "~/.config/rofi/appsearcher/config.rasi"
$wallpaper            =    bash ~/.config/rofi/wallsetter/wallsetter.sh
$powermenu            =    bash ~/.config/rofi/powermenu/powermenu.sh
$screenshot           =    grim -g "$(slurp)" - | wl-copy
$browser              =    firefox

# Essential Startup programs (Desktop Components)
# exec-once = hyprlock
exec-once = waybar &
exec-once = awww-daemon &
exec-once = nm-applet
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user start pipewire wireplumber pipewire-pulse

# Custom Programs or scripts
exec-once = ~/.scripts/connect-mic.sh
exec-once = rfkill block bluetooth
