# Hinterlands Theme Visuals
general {
    gaps_in = 5
    gaps_out = 0,10,10,10
    border_size = 1
    col.active_border = rgb(686868)
    col.inactive_border = rgb(222222)
    layout = dwindle
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0

    shadow {
        enabled = true
        range = 24
        render_power = 8
        color = rgba(000000ff)
    }

    blur {
        enabled = true
        size = 4
        passes = 3
    }
}

dwindle {
    pseudotile = true
    preserve_split = true
}
